spring:
  application:
    name: syfe

  datasource:
    url: jdbc:postgresql://ep-blue-dawn-aq4axvnn-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_8VCgqDN9XMmx
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  session:
    store-type: none
    timeout: 30m

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        name: SYFE_SESSION
        http-only: true
        same-site: strict
        max-age: 1800